spring.datasource.url=jdbc:mysql://localhost:3306/aiapp
spring.datasource.username=root
spring.datasource.password=Barath2244@

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
openrouter.api.key=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

server.port=8084


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bpersonal2005@gmail.com
spring.mail.password=barath2244@

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true